// Utility for CSV export functionality
export function exportToCSV(
  records: any[],
  filename: string = "cleaned_data.csv"
): void {
  if (!records || records.length === 0) {
    console.error("No records to export");
    return;
  }

  // Get headers from first record
  const headers = Object.keys(records[0]);

  // Create CSV content
  let csv = headers.join(",") + "\n";
  records.forEach((record) => {
    const values = headers.map((header) => {
      const value = record[header];
      // Escape quotes and wrap in quotes if contains comma
      if (typeof value === "string" && (value.includes(",") || value.includes('"'))) {
        return `"${value.replace(/"/g, '""')}"`;
      }
      return value || "";
    });
    csv += values.join(",") + "\n";
  });

  // Create blob and download
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);

  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  link.style.visibility = "hidden";

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function parseCSV(csvContent: string): Record<string, any>[] {
  const lines = csvContent.trim().split("\n");
  if (lines.length < 2) {
    return [];
  }

  const headers = lines[0].split(",").map((h) => h.trim());
  const records: Record<string, any>[] = [];

  for (let i = 1; i < lines.length; i++) {
    const values = parseCSVLine(lines[i]);
    if (values.length === headers.length) {
      const record: Record<string, any> = {};
      headers.forEach((header, index) => {
        record[header] = values[index];
      });
      records.push(record);
    }
  }

  return records;
}

function parseCSVLine(line: string): string[] {
  const values: string[] = [];
  let currentValue = "";
  let insideQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];

    if (char === '"') {
      if (insideQuotes && line[i + 1] === '"') {
        currentValue += '"';
        i++;
      } else {
        insideQuotes = !insideQuotes;
      }
    } else if (char === "," && !insideQuotes) {
      values.push(currentValue.trim());
      currentValue = "";
    } else {
      currentValue += char;
    }
  }

  values.push(currentValue.trim());
  return values;
}

export function generatePDFReport(data: any): void {
  // This is a placeholder - in production, use a library like jsPDF
  // For now, we'll show a simple implementation
  const content = formatReportContent(data);
  const blob = new Blob([content], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  window.open(url, "_blank");
}

function formatReportContent(data: any): string {
  return `
SmartSync AI - Data Quality Report

Generated: ${new Date().toLocaleDateString()}

Data Quality Metrics:
- Total Records: ${data.metrics?.totalRecords || 0}
- Quality Score: ${data.metrics?.qualityScore || 0}%
- Completeness Score: ${data.metrics?.completenessScore || 0}%
- Duplicate Rate: ${data.metrics?.duplicateRate || 0}%
- Missing Fields: ${data.metrics?.missingFields || 0}
- Invalid Emails: ${data.metrics?.invalidEmails || 0}
- Invalid Phones: ${data.metrics?.invalidPhones || 0}

AI Recommendations:

Quality Improvements:
${data.recommendations?.qualityImprovements?.map((item: string) => `- ${item}`).join("\n") || "N/A"}

Data Collection Suggestions:
${data.recommendations?.dataCollectionSuggestions?.map((item: string) => `- ${item}`).join("\n") || "N/A"}

CRM Optimizations:
${data.recommendations?.crmOptimizations?.map((item: string) => `- ${item}`).join("\n") || "N/A"}

---
Report generated by SmartSync AI
  `;
}
